export const stages=[
 {name:'Entrada e acolhimento',short:'Entrada',verb:'A história começa',icon:'🎀',color:0xc33e40,pos:[-7,0,-8.2],camera:[-7,11,2],focus:[-7,0,-8],text:'A família entra em um Natal ainda incompleto e recebe uma identidade compartilhada. A Fita de Autoria é uma hipótese conceitual, não uma tecnologia definida.',quote:'“Guardem esta fita. Ela vai lembrar o que vocês fizeram.”'},
 {name:'Tortuguita',short:'Tortuguita',verb:'Imaginar',icon:'🐢',color:0x338760,pos:[-6.4,0,-2.5],camera:[-13,9,-0.5],focus:[-6.3,0,-2.5],text:'A criança escolhe como seu Natal começa. Essa escolha gera um sinal reconhecível que reaparecerá ao final da experiência.',quote:'“Essa é a nossa.”'},
 {name:'Block',short:'Block',verb:'Fazer acontecer',icon:'⚡',color:0x225ecb,pos:[-6.2,0,5.3],camera:[-13,10,11],focus:[-6.2,0,5.3],text:'Construir, tentar, movimentar e vencer pequenos desafios transforma uma ideia em consequência real. O cenário responde ao esforço da família.',quote:'“Nós fizemos isso acontecer.”'},
 {name:'Butter Toffees',short:'Butter Toffees',verb:'Encontrar o outro',icon:'🤝',color:0xc68d51,pos:[6.0,0,4.9],camera:[13,9,11],focus:[6.0,0,4.9],text:'A família desacelera e descobre que vencer sozinho ou mais rápido não basta: é preciso ceder, esperar e sincronizar o próprio ritmo ao do outro.',quote:'“Só aconteceu porque fizemos juntos.”'},
 {name:'Clímax Arcor',short:'Clímax',verb:'Reconhecer',icon:'✦',color:0xd1a45c,pos:[0.8,0,0.7],camera:[12,12,15],focus:[0.8,3.3,0.7],text:'O ambiente revela sinais identificáveis das escolhas e ações da família. As contribuições coletivas enriquecem, mas uma única família deve viver um clímax completo.',quote:'“A nossa está ali.”'},
 {name:'Bon o Bon',short:'Bon o Bon',verb:'Passar adiante',icon:'🎁',color:0xbf3d45,pos:[6.6,0,-5.2],camera:[12,9,-10],focus:[6.6,0,-5.2],text:'O que foi construído ganha significado de presente. Bon o Bon transforma a conquista em um gesto para guardar e compartilhar, não em uma recompensa desconectada.',quote:'“Um é nosso. O outro é para alguém.”'},
 {name:'Saída',short:'Saída',verb:'O Natal continua',icon:'↗',color:0xdca85d,pos:[6,0,-9],camera:[13,9,-13],focus:[6,0,-9],text:'A família sai como autora de algo que não estava pronto quando chegou. O Natal continua na forma como as pessoas cuidam umas das outras.',quote:'“O Natal que criamos continua com você.”'}
];

export const symbols = [{id:"star", label:"Estrela", glyph:"★"}, {id:"heart", label:"Coração", glyph:"♥"}, {id:"tree", label:"Árvore", glyph:"▲"}, {id:"gift", label:"Presente", glyph:"▣"}];
export const pieces = [{id:"base", label:"Base", glyph:"▰"}, {id:"bridge", label:"Ponte", glyph:"∩"}, {id:"spark", label:"Luz", glyph:"✦"}];
